name: MacOS source build
run-name: MacOS source build
on:
   push:
     paths:
     - 'dobuild'
     - '**.yml'
jobs:
   Source-build:
     runs-on: macos-latest
     steps:
     - name: Check out repository
       uses: actions/checkout@v4
     - name: Build
       shell: bash
       run: |
          brew install xquartz --cask
          sh dobuild -- F77=gfortran-11 CC=gcc-11
     - name: Test for success
       shell: bash
       run: |
          if [ -f /usr/local/bin/sac ] ; then
             ( echo 'message "build successful"' ; echo 'quit' ) |
                 /usr/local/bin/sac > prog.out
             echo 'Build success:' | cat - prog.out >> $GITHUB_STEP_SUMMARY
          else
             echo 'Build fail' >> $GITHUB_STEP_SUMMARY
          fi
